[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "mcp-dagger-module"
version = "0.1.0"
dependencies = [
    "dagger-io",
]

[tool.hatch.build.targets.wheel]
packages = ["."] 